### ISSUE TITLE
Rebrand as “JSON API Browser” and release to the public

### ISSUE THREAD

**Issue by aviflax** [sfx/json-api-browser#1]
- [x] Rename the repo
- [ ] Update the docs
- [ ] Search for all mentions of the old name and update them
- [ ] Update the copyright notice to make clear that some of the code is copyright the original author and some is copyright SFX
- [ ] Make the repo public
- [ ] blog, tweet, etc
- [ ] …
- [ ] profit!

**Comment by closacco** [comment]
Yes! :sparkles:
